stages:
  - export

export_parts:
  stage: export
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - add-apt-repository -y ppa:freecad-maintainers/freecad-stable
    - apt-get update
    - apt-get install -y freecad freecad-python3 python3-pyqt5
  script:
    - freecadcmd export_parts.py
  artifacts:
    paths:
      - exports/

