stages:
  - export

export_parts:
  stage: export
  image:  ghcr.io/freecad/freecad-docker:latest
  script:
    - apt-get update && apt-get install -y python3 python3-pyqt5
    - python3 export_parts.py
  artifacts:
    paths:
      - exports/
